CATEGORIES = {
    "telefonia": [
        "smartphone-e-cellulari",
        "servizi",
        "iphone",
        "telefonia-fissa",
        "indossabili",
        "apple-watch",
    ],
    "computer-e-smart-home": [
        "computer",
        "mac",
        "servizi",
        "componenti-pc",
        "periferiche-pc-e-accessori",
        "stampa",
        "tablet",
        "ipad",
        "ebook-reader",
        "software",
        "ufficio",
        "smart-home-sicurezza",
        "smart-home-comfort",
        "smart-home-energia",
    ],
}
